### ISSUE TITLE
[BUG]: Cannot cast object dtype to float64

### ISSUE THREAD

**Issue by Nitro963** [pycaret/pycaret#4148]
### pycaret version checks

- [x] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [x] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [x] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Incorrect encoding or imputation for categorical variables 

### Reproducible Example

```python
import pandas as pd
from pycaret.classification import *

df = pd.DataFrame({'id': {0: 462809, 1: 462643, 2: 466315, 3: 461735, 4: 462669},
 'gender': {0: 'Male', 1: 'Female', 2: 'Female', 3: 'Male', 4: 'Female'},
 'ever_married': {0: False, 1: True, 2: True, 3: True, 4: True},
 'age': {0: 22, 1: 38, 2: 67, 3: 67, 4: 40},
 'graduated': {0: False, 1: True, 2: True, 3: True, 4: True},
 'profession': {0: 'Healthcare',
  1: 'Engineer',
  2: 'Engineer',
  3: 'Lawyer',
  4: 'Entertainment'},
 'work_experience': {0: 1.0, 1: None, 2: 1.0, 3: 0.0, 4: None},
 'spending_score': {0: 'Low', 1: 'Average', 2: 'Low', 3: 'High', 4: 'High'},
 'family_size': {0: 4.0, 1: 3.0, 2: 1.0, 3: 2.0, 4: 6.0},
 'target': {0: 3, 1: 2, 2: 2, 3: 2, 4: 3},
 'orginal_segmentation': {0: 3, 1: 0, 2: 1, 3: 1, 4: 0}}).astype({'id': 'int64',
 'gender': 'category',
 'ever_married': 'O',
 'age': 'int64',
 'graduated': 'O',
 'profession': 'category',
 'work_experience': 'float64',
 'spending_score': 'category',
 'family_size': 'float64',
 'target': 'int64',
 'orginal_segmentation': 'int64'})

s = setup(df.drop('target', axis=1), target = df['target'], categorical_features=list(df.columns.drop('target')), session_id = 123)
```

### Expected Behavior

It is expected to correctly encode categorical variables into integers or one hot encoded variables rather than casting to `float64` object.

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.11/dist-packages/pandas/core/arrays/categorical.py in astype(self, dtype, copy)
    590             try:
--> 591                 new_cats = new_cats.astype(dtype=dtype, copy=copy)
    592                 fill_value = self.categories._na_value

ValueError: could not convert string to float: 'Female'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
22 frames
/usr/local/lib/python3.11/dist-packages/pandas/core/arrays/categorical.py in astype(self, dtype, copy)
    600             ):
    601                 msg = f"Cannot cast {self.categories.dtype} dtype to {dtype}"
--> 602                 raise ValueError(msg)
    603 
    604             result = take_nd(

ValueError: Cannot cast object dtype to float64
```

### Installed Versions

System:
    python: 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]
executable: /usr/bin/python3
   machine: Linux-6.1.85+-x86_64-with-glibc2.35

PyCaret required dependencies:
                 pip: 24.1.2
          setuptools: 75.1.0
             pycaret: 3.4.0
             IPython: 7.34.0
          ipywidgets: 7.7.1
                tqdm: 4.67.1
               numpy: 1.26.4
              pandas: 2.2.2
              jinja2: 3.1.5
               scipy: 1.11.4
              joblib: 1.3.2
             sklearn: 1.6.1
                pyod: 2.0.3
            imblearn: 0.13.0
   category_encoders: 2.8.0
            lightgbm: 4.5.0
               numba: 0.61.0
            requests: 2.32.3
          matplotlib: 3.7.5
          scikitplot: 0.3.12
         yellowbrick: 1.5
              plotly: 5.24.1
    plotly-resampler: Not installed
             kaleido: 0.2.1
           schemdraw: 0.15
         statsmodels: 0.14.4
              sktime: 0.36.0
               tbats: 1.1.3
            pmdarima: 2.0.4
              psutil: 5.9.5
          markupsafe: 3.0.2
             pickle5: Not installed
         cloudpickle: 3.1.1
         deprecation: 2.1.0
              xxhash: 3.5.0
           wurlitzer: 3.1.1

PyCaret optional dependencies:
                shap: 0.46.0
           interpret: Not installed
                umap: Not installed
     ydata_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
          deepchecks: Not installed
             xgboost: 2.1.4
            catboost: Not installed
              kmodes: Not installed
             mlxtend: 0.23.4
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: 0.2.7
              optuna: Not installed
               skopt: Not installed
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: 1.1.6

**Comment by Ravikumarchavva** [comment]
I think the error coming pandas data type issue. 
Make the datatypes to below format
 **'ever_married': 'bool',**
 **'graduated': 'bool',**

and its working. you have kept these data types as 'O'

**Comment by jimilibilibob** [comment]
Hello @Nitro963 !

Try to set `imputation_type="iterative"` in your setup configuration. That's solve the problem for me

**Comment by DucNgMinh** [comment]
i think there is a problem with pandas because when i'm use categorical_imputation="mode", numeric_imputation=0.0, the bug also happen to me

**Comment by Gunasekara98620** [comment]
In your code
`s = setup(df.drop('target', axis=1), target=df['target'], categorical_features=list(df.columns.drop('target')), session_id=123)
`
you've specified all features (including numeric ones like age, family_size, and work_experience) as categorical. This causes PyCaret to apply one-hot encoding to all of them.

Why This Is Problematic:
- Columns like age often contain many unique values (e.g., each person might have a different age). One-hot encoding will create one binary column per unique age.
- Applying one-hot encoding to such features results in one binary column per unique value, leading to:
High-dimensional sparse matrices
Increased memory usage
Risk of overfitting
Poor model generalization

✅ Recommendation:
Treat age, family_size, and work_experience as numeric features, not categorical. If you still want to treat them categorically (e.g., to represent age groups), consider binning first.
Update your setup() like this:
`s = setup(
    data=df.drop('target', axis=1),
    target='target',
    categorical_features=['gender', 'ever_married', 'graduated', 'profession', 'spending_score'],
    session_id=123
)
`

This ensures:
- Only true categorical features are encoded.
- Numerical features are handled correctly by scaling or imputation.

**Comment by DucNgMinh** [comment]
@Gunasekara98620  I have followed your suggestion, but I still got the same result

**Reproducible Example:**
```
import pandas as pd
from pycaret.classification import *
df = (
    pd.DataFrame({
        'id': {0: 462809, 1: 462643, 2: 466315, 3: 461735, 4: 462669},
        'gender': {0: 'Male', 1: 'Female', 2: 'Female', 3: 'Male', 4: 'Female'},
        'ever_married': {0: False, 1: True, 2: True, 3: True, 4: True},
        'age': {0: 22, 1: 38, 2: 67, 3: 67, 4: 40},
        'graduated': {0: False, 1: True, 2: True, 3: True, 4: True},
        'profession': {0: 'Healthcare',
                    1: 'Engineer',
                    2: 'Engineer',
                    3: 'Lawyer',
                    4: 'Entertainment'},
        'work_experience': {0: 1.0, 1: None, 2: 1.0, 3: 0.0, 4: None},
        'spending_score': {0: 'Low', 1: 'Average', 2: 'Low', 3: 'High', 4: 'High'},
        'family_size': {0: 4.0, 1: 3.0, 2: 1.0, 3: 2.0, 4: 6.0},
        'target': {0: 3, 1: 2, 2: 2, 3: 2, 4: 3},
    'orginal_segmentation': {0: 3, 1: 0, 2: 1, 3: 1, 4: 0}
    })
    .astype({
        'id': 'int64',
        'gender': 'category',
        'ever_married': 'category',
        'age': 'int64',
        'graduated': 'category',
        'profession': 'category',
        'work_experience': 'float64',
        'spending_score': 'category',
        'family_size': 'float64',
        'target': 'int64',
        'orginal_segmentation': 'int64'
    })
)

s = setup(
    data=df, 
    target='target', 
    ignore_features=["id"],
    numeric_features=['age', 'family_size', 'orginal_segmentation', 'work_experience'],
    categorical_features=['gender', 'ever_married', 'graduated', 'profession', 'spending_score'], 

    preprocess=True,
    imputation_type="simple",
    categorical_imputation="mode",
    numeric_imputation=0.0,

    session_id=123 
)

```
**Result:**
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File c:\Users\admin\Documents\Dump\.venv\lib\site-packages\pandas\core\arrays\categorical.py:564, in Categorical.astype(self, dtype, copy)
    563 try:
--> [564](file:///C:/Users/admin/Documents/Dump/.venv/lib/site-packages/pandas/core/arrays/categorical.py:564)     new_cats = new_cats.astype(dtype=dtype, copy=copy)
    565     fill_value = self.categories._na_value

ValueError: could not convert string to float: 'Female'

During handling of the above exception, another exception occurred:
```

**Installed Versions:**
```
System:
    python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
executable: [c:\Users\admin\Documents\Dump\.venv\Scripts\python.exe](file:///C:/Users/admin/Documents/Dump/.venv/Scripts/python.exe)
   machine: Windows-10-10.0.19045-SP0

PyCaret required dependencies:
                 pip: 22.0.4
          setuptools: 80.9.0
             pycaret: 3.3.2
             IPython: 8.18.1
          ipywidgets: 8.1.7
                tqdm: 4.67.1
               numpy: 1.26.4
              pandas: 2.1.4
              jinja2: 3.1.6
               scipy: 1.11.4
              joblib: 1.3.2
             sklearn: 1.4.2
                pyod: 2.0.5
            imblearn: 0.12.4
   category_encoders: 2.6.4
            lightgbm: 4.6.0
               numba: 0.60.0
            requests: 2.32.4
          matplotlib: 3.7.5
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.24.1
    plotly-resampler: Not installed
             kaleido: 1.0.0
           schemdraw: 0.15
         statsmodels: 0.14.5
              sktime: 0.26.0
               tbats: 1.1.3
            pmdarima: 2.0.4
              psutil: 7.0.0
          markupsafe: 2.1.5
             pickle5: Not installed
         cloudpickle: 3.1.1
         deprecation: 2.1.0
              xxhash: 3.5.0
           wurlitzer: Not installed

PyCaret optional dependencies:
                shap: 0.44.1
           interpret: 0.7.2
                umap: 0.5.7
     ydata_profiling: 4.16.1
  explainerdashboard: 0.5.1
             autoviz: Not installed
           fairlearn: 0.7.0
          deepchecks: Not installed
             xgboost: 2.1.4
            catboost: 1.2.1
              kmodes: 0.12.2
             mlxtend: 0.23.4
       statsforecast: 1.5.0
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: 0.2.7
              optuna: 4.4.0
               skopt: 0.10.2
              mlflow: 2.21.3
              gradio: Not installed
             fastapi: 0.116.1
             uvicorn: 0.22.0
              m2cgen: 0.10.0
           evidently: 0.4.40
               fugue: 0.8.7
           streamlit: Not installed
             prophet: Not installed
```
